#!/bin/bash

if [[ $1 == "-h" || $1 == "--help" ]]; then
    programName=$(basename "$0")
    echo "Usage: ${programName} [options] [STL file] [STEP file or out Dir]"
    echo "Converts an STL file to a STEP file using FreeCAD."
    echo
    echo "Options:"
    echo "    -h, --help     Display this help message"
    echo 
    echo "Examples:"
    echo "    '${programName} file.stl'             creates file.step in the same directory."
    echo "    '${programName} file.stl myFile.step' creates myFile.step in the same directory."
    echo "    '${programName} file.stl ./outDir'    creates file.step in outDir directory."
    exit 0
fi
./squashfs-root/usr/bin/freecadcmd stl2step.py --pass "$@"